#!/usr/bin/env bash
# Adds the INTERNET permission and the cleartext-HTTP network config to the
# Android manifest generated by `flutter create`.
#
# Safe to run more than once — each edit is skipped if already applied.
# Works locally too, not just in CI.

set -euo pipefail

MANIFEST="android/app/src/main/AndroidManifest.xml"
XML_DIR="android/app/src/main/res/xml"
CONFIG="$XML_DIR/network_security_config.xml"

if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: $MANIFEST not found. Run 'flutter create --platforms=android .' first."
  exit 1
fi

# 1. Network security config — allows plain http:// to the dev backend hosts
#    only, instead of turning cleartext on for the whole app.
mkdir -p "$XML_DIR"
cat > "$CONFIG" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">127.0.0.1</domain>
        <!-- Developer machine on the local network -->
        <domain includeSubdomains="true">192.168.1.15</domain>
    </domain-config>
</network-security-config>
EOF
echo "Wrote $CONFIG"

# 2. INTERNET permission
if grep -q 'android.permission.INTERNET' "$MANIFEST"; then
  echo "INTERNET permission already present."
else
  sed -i 's|<manifest\(.*\)>|<manifest\1>\n    <uses-permission android:name="android.permission.INTERNET"/>|' "$MANIFEST"
  echo "Added INTERNET permission."
fi

# 3. Point <application> at the network security config
if grep -q 'networkSecurityConfig' "$MANIFEST"; then
  echo "networkSecurityConfig already present."
else
  sed -i 's|<application|<application\n        android:networkSecurityConfig="@xml/network_security_config"|' "$MANIFEST"
  echo "Added networkSecurityConfig attribute."
fi

echo "Android network configuration applied."
